using Content.Shared.Clothing;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Utility;

namespace Content.Client._Starfall.UserInterface.Lobby.Loadouts;

/// <summary>
/// A card representing a loadout item in the Starfall loadout editor.
/// Displays the loadout item's name, cost, and icon, and allows the user to select or deselect the loadout item.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class StarfallLoadoutItemCard : ContainerButton
{
    [Dependency] private IEntityManager _entityManager = null!;

    private EntityUid? _previewEntity;
    private bool _suppressSelectionEvent;

    public event Action<bool>? SelectionChanged;
    private const int MaximumDisplayedNameLength = 24;

    public StarfallLoadoutItemCard()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        OnToggled += args =>
        {
            if (_suppressSelectionEvent)
                return;

            SelectionChanged?.Invoke(args.Pressed);
        };
    }

    public void Configure(
        LoadoutPrototype prototype,
        string name,
        int cost,
        bool showCost,
        bool selected,
        bool disabled,
        FormattedMessage? disabledReason)
    {
        // Some loadout names can be very long, so we truncate them to a reasonable length.
        // TODO: Since the text is centered it actually ends up clipping both left/right sides
        //       so uh, fix that!
        ItemNameLabel.Text =
            name.Length <= MaximumDisplayedNameLength
                ? name
                : name.Substring(
                        0,
                        MaximumDisplayedNameLength - 1)
                    .TrimEnd() + "…";

        ItemNameLabel.ToolTip = name;
        CostLabel.Text = cost.ToString();
        CostLabel.Visible = showCost;

        SetSelected(selected);
        Disabled = disabled;

        var loadoutSystem = _entityManager.System<LoadoutSystem>();

        var entityPrototype = prototype.DummyEntity ?? loadoutSystem.GetFirstOrNull(prototype);

        if (entityPrototype != null)
        {
            var previewEntity = _entityManager.SpawnEntity(entityPrototype, MapCoordinates.Nullspace);

            _previewEntity = previewEntity;
            ItemSprite.SetEntity(previewEntity);

            if (_entityManager.TryGetComponent<MetaDataComponent>(previewEntity, out var metadata))
            {
                ToolTip = metadata.EntityDescription;
            }
        }

        if (disabled && disabledReason != null)
        {
            var tooltip = new Tooltip();
            tooltip.SetMessage(disabledReason);
            TooltipSupplier = _ => tooltip;
        }
    }

    public void SetSelected(bool selected)
    {
        _suppressSelectionEvent = true;
        Pressed = selected;
        _suppressSelectionEvent = false;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        ItemSprite.SetEntity(null);
        _entityManager.TryQueueDeleteEntity(_previewEntity);
        _previewEntity = null;
    }
}
