version = 1
SPDX-PackageName = "Starfall Drift"
SPDX-PackageSupplier = "TrixxedHeart <trixxedheart@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/Starfall-Drift/Starfall-Drift"

[[annotations]]
path = ["Resources/Audio/**", "Resources/Textures/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["**.txt", "**.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "MIT"