using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;

namespace Content.Client._Starfall.UserInterface.Lobby.Traits;

/// <summary>
/// A card representing a trait in the Starfall traits editor.
/// Displays the trait's name, cost, and description, and allows the user to select or deselect the trait.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class StarfallTraitCard : Control
{
    public event Action<bool>? PreferenceChanged;

    // ᓚᘏᗢ <(We make the tooltip delay shorter so its quicker to see the trait description when hovering over the card
    private const float TraitTooltipDelay = 0.15f;

    public int Cost { get; }

    public bool Preference
    {
        get => Checkbox.Pressed;
        set
        {
            Checkbox.Pressed = value;
            UpdateSelectedState(value);
        }
    }

    public StarfallTraitCard()
    {
        RobustXamlLoader.Load(this);
    }

    public StarfallTraitCard(TraitPrototype trait) : this()
    {
        Cost = trait.Cost;

        NameLabel.Text = Loc.GetString(trait.Name);

        if (trait.Description is { } description)
        {
            var localizedDescription = Loc.GetString(description);

            ToolTip = localizedDescription;
            TooltipDelay = TraitTooltipDelay;

            Card.ToolTip = localizedDescription;
            Card.TooltipDelay = TraitTooltipDelay;

            Checkbox.ToolTip = localizedDescription;
            Checkbox.TooltipDelay = TraitTooltipDelay;

            NameLabel.ToolTip = localizedDescription;
            NameLabel.TooltipDelay = TraitTooltipDelay;

            CostLabel.ToolTip = localizedDescription;
            CostLabel.TooltipDelay = TraitTooltipDelay;
        }

        Checkbox.OnToggled += OnCheckBoxToggled;

        UpdateCost();
        UpdateSelectedState(false);
    }

    public void SetUnavailable(bool unavailable)
    {
        Checkbox.Disabled = unavailable;
        Card.Modulate = unavailable ? Color.FromHex("#9da6b0") : Color.White;
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Handled || args.Function != EngineKeyFunctions.UIClick || Checkbox.Disabled)
            return;

        Preference = !Preference;
        PreferenceChanged?.Invoke(Preference);

        args.Handle();
    }

    private void OnCheckBoxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        UpdateSelectedState(args.Pressed);
        PreferenceChanged?.Invoke(args.Pressed);
    }

    // Updates the cost label and its color based on the trait's cost.
    private void UpdateCost()
    {
        // If the cost is positive (uses points), we display it in red with a "+" sign.
        if (Cost > 0)
        {
            CostLabel.Text = $"+{Cost}";
            CostLabel.Modulate = Color.FromHex("#ff555d");
        }
        // If the cost is negative (gives points), we display it in green
        else if (Cost < 0)
        {
            CostLabel.Text = Cost.ToString();
            CostLabel.Modulate = Color.FromHex("#55d975");
        }
        // If the cost is zero, we display it in a neutral color.
        else
        {
            CostLabel.Text = "0";
            CostLabel.Modulate = Color.FromHex("#8997a3");
        }
    }

    private void UpdateSelectedState(bool selected)
    {
        Card.RemoveStyleClass("StarfallTraitSelected");

        if (selected)
            Card.AddStyleClass("StarfallTraitSelected");
    }
}
