using System.Linq;
using Content.Shared.Preferences;
using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Starfall.UserInterface.Lobby.Traits;

/// <summary>
/// Displays the character's available traits as cards and manages trait point limits.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class StarfallTraitsEditor : BoxContainer
{
    [Dependency] private IPrototypeManager _prototypeManager = null!;

    private HumanoidCharacterProfile? _profile;

    /// <summary>
    /// Raised when selecting or removing a trait produces a replacement character profile.
    /// </summary>
    public event Action<HumanoidCharacterProfile>? ProfileChanged;

    public StarfallTraitsEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetProfile(HumanoidCharacterProfile? profile)
    {
        _profile = profile;
        RefreshTraits();
    }

    public void SyncProfile(HumanoidCharacterProfile? profile)
    {
        _profile = profile;
    }

    /// <summary>
    /// Rebuilds all trait categories, point counters, and trait cards from the currently loaded prototypes and profile.
    /// </summary>
    public void RefreshTraits()
    {
        TraitsList.RemoveAllChildren();

        var traits = _prototypeManager
            .EnumeratePrototypes<TraitPrototype>()
            .OrderBy(trait =>
                Loc.GetString(trait.Name))
            .ToList();

        // ᓚᘏᗢ <(This should never happen but whatever, people can be stupid god forbid
        if (traits.Count == 0)
        {
            TraitsList.AddChild(new Label
            {
                Text = Loc.GetString("humanoid-profile-editor-no-traits"),
                FontColorOverride = Color.Gray,
            });
            return;
        }

        // Group traits by category, with a default category for traits without a category.
        var traitGroups = new Dictionary<string, List<string>> { { TraitCategoryPrototype.Default, new List<string>() } };

        foreach (var trait in traits)
        {
            if (trait.Category == null)
            {
                traitGroups[TraitCategoryPrototype.Default].Add(trait.ID);
                continue;
            }

            // Ignore traits with invalid categories.
            if (!_prototypeManager.HasIndex(trait.Category))
                continue;

            var group = traitGroups.GetOrNew(trait.Category);
            group.Add(trait.ID);
        }

        foreach (var group in traitGroups)
        {
            var categoryId = group.Key;
            var categoryTraits = group.Value;

            TraitCategoryPrototype? category = null;

            if (categoryId != TraitCategoryPrototype.Default)
            {
                category = _prototypeManager.Index<TraitCategoryPrototype>(categoryId);
                AddCategoryHeader(category);
            }

            AddCategoryTraits(category, categoryTraits);
        }
    }

    /// <summary>
    /// Adds a header label for a trait category to the traits list.
    /// </summary>
    private void AddCategoryHeader(TraitCategoryPrototype category)
    {
        // ᓚᘏᗢ <(I HATEEE constructors that look like this
        TraitsList.AddChild(new PanelContainer
            {
                Margin = new Thickness(0, 10, 0, 6),
                StyleClasses =
                {
                    "StarfallProfileHeader",
                },
                Children =
                {
                    new Label
                    {
                        Text = Loc.GetString(category.Name),
                        StyleClasses =
                        {
                            "StarfallProfileTitle",
                        },
                    },
                },
            });
    }

    /// <summary>
    /// Creates the three-column grid of trait cards for a given category and adds it to the traits list, along with a point counter if applicable.
    /// </summary>
    private void AddCategoryTraits(TraitCategoryPrototype? category, List<string> categoryTraits)
    {
        var selectors = new List<StarfallTraitCard>();
        var selectionCount = 0;
        var traitGrid = new GridContainer
            {
                Columns = 3,
                HorizontalExpand = true,
                HSeparationOverride = 8,
                VSeparationOverride = 8,
            };

        foreach (var traitId in categoryTraits)
        {
            var trait = _prototypeManager.Index<TraitPrototype>(traitId);
            var selector = new StarfallTraitCard(trait)
                {
                    HorizontalExpand = true,
                };

            selector.Preference = _profile?.TraitPreferences.Contains(trait.ID) == true;

            if (selector.Preference)
                selectionCount += trait.Cost;

            selector.PreferenceChanged += preference =>
                {
                    ChangeTraitPreference(
                        trait,
                        preference);
                };

            selectors.Add(selector);
        }

        // A missing point limit is represented by a negative number, so we use that to determine whether to show a point counter.
        var maximumPoints = category?.MaxTraitPoints ?? -1;

        if (maximumPoints >= 0)
            AddPointCounter(selectionCount, maximumPoints);

        TraitsList.AddChild(traitGrid);

        foreach (var selector in selectors)
        {
            // Selected traits remain available so the player can always
            // deselect them. Only unselected traits that would exceed the
            // limit are disabled.
            var unavailable = maximumPoints >= 0 && !selector.Preference && selector.Cost + selectionCount > maximumPoints;

            selector.SetUnavailable(unavailable);
            traitGrid.AddChild(selector);
        }
    }

    /// <summary>
    /// Adds a category point counter and highlights it when all available points have been used.
    /// </summary>
    private void AddPointCounter(int selectionCount, int maximum)
    {
        var limitReached = maximum > 0 && selectionCount >= maximum;
        TraitsList.AddChild(new Label
        {
            Text = Loc.GetString("humanoid-profile-editor-trait-count-hint", ("current", selectionCount), ("max", maximum)),
            FontColorOverride = limitReached ? Color.FromHex("#ff555d") : Color.FromHex("#9eabb5"),
        });
    }

    /// <summary>
    /// Applies a trait preference change to the current profile and raises the ProfileChanged event.
    /// </summary>
    private void ChangeTraitPreference(TraitPrototype trait, bool preference)
    {
        if (_profile == null)
            return;

        _profile = preference
            ? _profile.WithTraitPreference(trait.ID, _prototypeManager)
            : _profile.WithoutTraitPreference(trait.ID, _prototypeManager);

        ProfileChanged?.Invoke(_profile);

        // Recalculate counters and availability using the updated profile.
        RefreshTraits();
    }
}
