using Content.Client.Message;
using Content.Client.Resources;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starfall.UserInterface.Lobby.Roles;

/// <summary>
/// A card representing an antagonist role in the Starfall lobby.
/// Displays the role's name, description, and icon, and allows the user to view the role's guidebook and set their preference for the role.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class StarfallAntagCard : PanelContainer
{
    private const string PlaceholderPath = "/Textures/Interface/Nano/placeholder.png";

    private bool _suppressPreferenceEvent;

    [Dependency] private IResourceCache _resourceCache = null!;

    public event Action? OnGuidebookClicked;
    public event Action<bool>? PreferenceChanged;
    private bool _guidebookAvailable;

    public StarfallAntagCard()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        GuidebookButton.OnPressed += _ =>
        {
            if (_guidebookAvailable)
                OnGuidebookClicked?.Invoke();
        };

        PreferenceToggle.OnToggled += args =>
        {
            if (_suppressPreferenceEvent)
                return;

            PreferenceChanged?.Invoke(args.Pressed);
        };

        AntagDescription.OnResized += UpdateDescriptionHeight;
        OnResized += UpdateDescriptionHeight;
    }

    public void SetIcon(Texture? texture)
    {
        Icon.Texture = texture ?? _resourceCache.GetTexture(PlaceholderPath);
    }

    public void SetDescription(string description)
    {
        AntagDescription.SetMarkupPermissive(description);
    }

    public void SetPreference(bool enabled)
    {
        _suppressPreferenceEvent = true;
        PreferenceToggle.Pressed = enabled;
        _suppressPreferenceEvent = false;
    }

    public void SetPreferenceLocked(bool locked)
    {
        PreferenceToggle.Disabled = locked;
        Modulate = locked ? Color.FromHex("#687078") : Color.White;
    }

    // TODO: ᓚᘏᗢ <( me when i duplicate code
    public void SetGuidebookAvailable(bool available)
    {
        _guidebookAvailable = available;
        GuidebookButton.ToolTip = available ? Loc.GetString("humanoid-profile-editor-guidebook-button-tooltip") : null;
    }

    private void UpdateDescriptionHeight()
    {
        const float minimumDescriptionHeight = 72f;
        const float descriptionPadding = 14f;
        const float headerHeight = 54f;
        const float cardPadding = 16f;
        const float separation = 7f;

        var descriptionHeight = MathF.Max(minimumDescriptionHeight, AntagDescription.DesiredSize.Y + descriptionPadding);
        var requiredCardHeight = headerHeight + separation + descriptionHeight + cardPadding;

        if (MathF.Abs(MinHeight - requiredCardHeight) < 0.5f)
            return;

        DescriptionPanel.MinHeight = descriptionHeight;
        MinHeight = requiredCardHeight;

        // ᓚᘏᗢ <(make sure the parent containers update their layout as well because it hates me
        Control? current = this;

        while (current != null)
        {
            current.InvalidateMeasure();
            current.InvalidateArrange();
            current = current.Parent;
        }
    }

    public void SetName(string name)
    {
        AntagName.Text = name;

        var fontSize = name.Length switch
        {
            > 24 => 12,
            > 20 => 13,
            > 17 => 14,
            _ => 16,
        };

        AntagName.FontOverride = _resourceCache.GetFont("/Fonts/NotoSans/NotoSans-Bold.ttf", fontSize);
    }
}
