using System.Linq;
using Content.Client.Players.PlayTimeTracking;
using Content.Shared.Clothing;
using Content.Shared.GameTicking;
using Content.Shared.Guidebook;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Starfall.UserInterface.Lobby.Roles;

/// <summary>
/// Displays the character's available jobs and antags as cards and manages job/antag preferences.
/// Currently only supports a single character profile, but is designed to support multiple profiles in the future.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class StarfallRolesEditor :
    BoxContainer
{
    [Dependency] private IPrototypeManager _prototypeManager = null!;
    [Dependency] private IEntityManager _entityManager = null!;
    [Dependency] private JobRequirementsManager _requirements = null!;

    /// <summary>
    /// Maps each department-filter option to its prototype ID.
    /// A null entry represents the unfiltered "All departments" option.
    /// </summary>
    private readonly List<string?> _jobDepartmentFilters = new();

    private readonly SpriteSystem _sprite;

    private HumanoidCharacterProfile? _profile;
    private string? _selectedJobDepartment;

    /// <summary>
    /// Raised whenever job, antag, or preference changes produce a new character profile.
    /// </summary>
    public event Action<HumanoidCharacterProfile>? ProfileChanged;

    /// <summary>
    /// Raised when the player requests the loadout editor for a particular job.
    /// </summary>
    public event Action<JobPrototype>? LoadoutRequested;

    /// <summary>
    /// Raised when the player requests a preview of a particular job's loadout.
    /// </summary>
    public event Action<JobPrototype?>? PreviewJobChanged;

    /// <summary>
    /// Raised when the player requests to open a guidebook for a particular job or antag.
    /// </summary>
    public event Action<List<ProtoId<GuideEntryPrototype>>>? OpenGuidebookRequested;

    public StarfallRolesEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entityManager.System<SpriteSystem>();

        RolesTabContainer.SetTabTitle(0,Loc.GetString("humanoid-profile-editor-jobs-tab"));
        RolesTabContainer.SetTabTitle(1,Loc.GetString("humanoid-profile-editor-antags-tab"));

        PreferenceUnavailableButton.AddItem(
            Loc.GetString(
                "starfall-roles-unavailable-stay"),
            (int) PreferenceUnavailableMode.StayInLobby);

        PreferenceUnavailableButton.AddItem(
            Loc.GetString(
                "starfall-roles-unavailable-overflow",
                ("overflowJob",
                    Loc.GetString(
                        SharedGameTicker.FallbackOverflowJobName))),
            (int) PreferenceUnavailableMode.SpawnAsOverflow);

        PreferenceUnavailableButton.OnItemSelected +=
            args =>
            {
                PreferenceUnavailableButton.SelectId(args.Id);

                if (_profile == null)
                    return;

                _profile = _profile.WithPreferenceUnavailable((PreferenceUnavailableMode)args.Id);

                NotifyProfileChanged();
            };

        EnabledJobsHeader.OnPressed += _ =>
        {
            EnabledJobsPanel.Visible = !EnabledJobsPanel.Visible;

            // ᓚᘏᗢ <(Stupid
            EnabledJobsChevron.Text = EnabledJobsPanel.Visible
                ? "▼"
                : "▶";
        };

        JobSearch.OnTextChanged += _ =>
        {
            JobSearchClearButton.Disabled = string.IsNullOrEmpty(JobSearch.Text);

            RefreshJobs();
        };

        JobSearchClearButton.OnPressed += _ =>
        {
            JobSearch.Text = string.Empty;
            JobSearchClearButton.Disabled = true;
            RefreshJobs();
        };

        JobDepartmentFilter.OnItemSelected += args =>
            {
                JobDepartmentFilter.SelectId(args.Id);

                _selectedJobDepartment = args.Id >= 0 && args.Id < _jobDepartmentFilters.Count ? _jobDepartmentFilters[args.Id] : null;

                RefreshJobs();
            };

        JobSelectedOnly.OnToggled += _ =>
        {
            RefreshJobs();
        };
    }

    public void SetProfile(HumanoidCharacterProfile? profile)
    {
        SyncProfile(profile);
        RefreshJobs();
        RefreshAntags();
    }

    /// <summary>
    /// Synchronizes the editor with a new character profile
    /// </summary>
    public void SyncProfile(HumanoidCharacterProfile? profile)
    {
        _profile = profile;
    }

    /// <summary>
    /// Rebuilds all job and antag cards from the currently loaded prototypes and profile.
    /// </summary>
    public void RefreshJobs()
    {
        JobList.RemoveAllChildren();
        EnabledJobsList.RemoveAllChildren();

        var departments = _prototypeManager.EnumeratePrototypes<DepartmentPrototype>().Where(department => !department.EditorHidden).ToList();

        // Preserve upstream department ordering, including command positions.
        departments.Sort(DepartmentUIComparer.Instance);

        // A job may belong to more than one department. Heads of staff appear in Command as well as their primary department.
        var jobDepartments = BuildJobDepartmentMap(departments);

        var jobs = _prototypeManager.EnumeratePrototypes<JobPrototype>().Where(job => job.SetPreference && jobDepartments.ContainsKey(job.ID)).OrderBy(job => job.LocalizedName).ToList();

        SetupDepartmentFilter(departments);

        bool IsEnabled(JobPrototype job)
        {
            return _profile?.JobPriorities.GetValueOrDefault(job.ID, JobPriority.Never) != JobPriority.Never;
        }

        RefreshEnabledJobs(jobs, IsEnabled);

        var search = JobSearch.Text.Trim();

        var filtered = jobs.Where(job =>
            {
                if (JobSelectedOnly.Pressed && !IsEnabled(job))
                    return false;

                if (_selectedJobDepartment != null && !jobDepartments[job.ID].Contains(_selectedJobDepartment))
                    return false;

                if (search.Length == 0)
                    return true;

                return job.LocalizedName.Contains(
                           search,
                           StringComparison
                               .OrdinalIgnoreCase) ||
                       (job.LocalizedDescription
                            ?.Contains(
                                search,
                                StringComparison
                                    .OrdinalIgnoreCase)
                        ?? false);
            })
            .ToList();

        if (filtered.Count == 0)
        {
            JobList.AddChild(new Label
            {
                Text = "No jobs match these filters.",

                HorizontalAlignment = HAlignment.Center,

                Margin = new Thickness(8),
            });

            return;
        }

        foreach (var department in departments)
        {
            if (_selectedJobDepartment != null && department.ID != _selectedJobDepartment)
                continue;

            var departmentJobs = filtered
                .Where(job =>
                    department.Roles.Contains(job.ID) &&
                    (department.Primary ||
                     department.ID == "Command"))
                .OrderBy(
                    job => job,
                    JobUIComparer.Instance)
                .ToList();

            if (departmentJobs.Count == 0)
                continue;

            AddDepartmentHeader(department);
            AddDepartmentJobs(departmentJobs, IsEnabled);
        }
    }

    /// <summary>
    /// Rebuilds the three-column antagonist card grid and validates saved preferences against the character's current requirements.
    /// </summary>
    public void RefreshAntags()
    {
        AntagList.RemoveAllChildren();

        var antags = _prototypeManager
            .EnumeratePrototypes<AntagPrototype>()
            .Where(antag => antag.SetPreference)
            .OrderBy(antag =>
                Loc.GetString(antag.Name))
            .ToList();

        BoxContainer? row = null;
        var column = 0;

        foreach (var antag in antags)
        {
            if (column == 0)
            {
                row = CreateCardRow();
                AntagList.AddChild(row);
            }

            var card =
                new StarfallAntagCard
                {
                    HorizontalExpand = true,
                    VerticalExpand = true,
                    MinWidth = 300,
                };

            card.SetName(
                Loc.GetString(antag.Name));

            card.SetDescription(
                Loc.GetString(antag.Objective));

            card.SetGuidebookAvailable(antag.Guides is { Count: > 0 });

            card.OnGuidebookClicked += () =>
            {
                if (antag.Guides != null)
                {
                    OpenGuidebookRequested?.Invoke(antag.Guides);
                }
            };

            Texture? icon = null;

            if (antag.Icon != null)
                icon = _sprite.Frame0(antag.Icon);

            // StarfallAntagCard will use a placeholder icon if this is null.
            card.SetIcon(icon);

            var enabled =
                _profile?.AntagPreferences.Contains(antag.ID) == true;

            card.SetPreference(enabled);

            // Locked antagonists remain visible, so players can understand that they exist and inspect the unmet requirement tooltip
            if (!_requirements.IsAllowed(antag, _profile, out var reason))
            {
                card.SetPreference(false);
                card.SetPreferenceLocked(true);

                var tooltip = new Tooltip();
                tooltip.SetMessage(reason);
                card.TooltipSupplier = _ => tooltip;

                if (enabled && _profile != null)
                {
                    _profile = _profile.WithAntagPreference(antag.ID, false);

                    NotifyProfileChanged();
                }
            }
            else
            {
                card.SetPreferenceLocked(false);
            }

            card.PreferenceChanged += preference =>
            {
                if (_profile == null)
                    return;

                _profile = _profile.WithAntagPreference(antag.ID, preference);

                NotifyProfileChanged();
            };

            row!.AddChild(card);

            column++;

            if (column == 3)
                column = 0;
        }

        if (row != null && column > 0)
        {
            for (var index = column; index < 3; index++)
            {
                row.AddChild(new Control
                {
                    HorizontalExpand = true,
                    MinWidth = 300,
                });
            }
        }
    }

    /// <summary>
    /// Builds a lookup containing every department associated with each job.
    /// A set is used to allow for jobs that belong to multiple departments, such as heads of staff.
    /// </summary>
    private Dictionary<string, HashSet<string>> BuildJobDepartmentMap(List<DepartmentPrototype> departments)
    {
        var result = new Dictionary<string, HashSet<string>>();

        foreach (var department in departments)
        {
            foreach (var jobId in department.Roles)
            {
                if (!result.TryGetValue(jobId, out var jobDepartmentSet))
                {
                    jobDepartmentSet = new HashSet<string>();

                    result[jobId] = jobDepartmentSet;
                }

                jobDepartmentSet.Add(department.ID);
            }
        }

        return result;
    }

    /// <summary>
    /// Populates the department filter dropdown with all available departments.
    /// </summary>
    private void SetupDepartmentFilter(List<DepartmentPrototype> departments)
    {
        if (_jobDepartmentFilters.Count != 0)
            return;

        JobDepartmentFilter.Clear();

        _jobDepartmentFilters.Add(null);

        JobDepartmentFilter.AddItem("All departments",0);

        foreach (var department in departments)
        {
            _jobDepartmentFilters.Add(department.ID);

            JobDepartmentFilter.AddItem(Loc.GetString(department.Name), _jobDepartmentFilters.Count - 1);
        }

        JobDepartmentFilter.SelectId(0);
    }

    /// <summary>
    /// Rebuilds the list of enabled jobs at the top of the editor, which is a horizontal row of buttons that can be clicked to disable the job.
    /// </summary>
    private void RefreshEnabledJobs(List<JobPrototype> jobs, Func<JobPrototype, bool> isEnabled)
    {
        var enabledJobs = jobs.Where(isEnabled).ToList();

        EnabledJobsCount.Text = enabledJobs.Count.ToString();

        if (enabledJobs.Count == 0)
        {
            EnabledJobsList.AddChild(new Label
            {
                Text = "No jobs enabled.",

                FontColorOverride = Color.FromHex("#9aa8b2"), // ᓚᘏᗢ <(me when i hardcode colors in code
            });

            return;
        }

        BoxContainer? row = null;
        var column = 0;

        foreach (var job in enabledJobs)
        {
            if (column == 0)
            {
                row = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    SeparationOverride = 6,
                    Margin = new Thickness(0, 0, 0, 6),
                };

                EnabledJobsList.AddChild(row);
            }

            var chip = new Button
            {
                Text = $"{job.LocalizedName} ×",

                ToolTip = $"Disable {job.LocalizedName}",

                HorizontalExpand = true,
                Margin = new Thickness(2),
            };

            chip.OnPressed += _ =>
            {
                SetJobEnabled(job, false);
            };

            row!.AddChild(chip);

            column = (column + 1) % 4;
        }

        if (row == null || column == 0)
            return;

        for (var index = column; index < 4; index++)
        {
            row.AddChild(new Control
            {
                HorizontalExpand = true,
            });
        }
    }

    /// <summary>
    /// Adds a department header label to the job list.
    /// </summary>
    private void AddDepartmentHeader(DepartmentPrototype department)
    {
        var header = new PanelContainer
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 4, 0, 8),
        };

        header.StyleClasses.Add("StarfallProfileHeader");

        var label = new Label
        {
            Text = Loc.GetString(department.Name),

            Margin = new Thickness(6, 2),
        };

        label.StyleClasses.Add("StarfallProfileTitle");

        header.AddChild(label);
        JobList.AddChild(header);
    }

    /// <summary>
    /// Adds a horizontal row of job cards for a department to the job list.
    /// </summary>
    private void AddDepartmentJobs(List<JobPrototype> jobs, Func<JobPrototype, bool> isEnabled)
    {
        BoxContainer? row = null;
        var column = 0;

        foreach (var job in jobs)
        {
            if (column == 0)
            {
                row = CreateCardRow();
                JobList.AddChild(row);
            }

            var card = new StarfallJobCard
                {
                    HorizontalExpand = true,
                    VerticalExpand = true,
                };

            card.SetName(job.LocalizedName);

            card.SetDescription(job.LocalizedDescription ?? string.Empty);

            var jobIcon = _prototypeManager.Index(job.Icon);

            card.SetIcon(_sprite.Frame0(jobIcon.Icon));

            card.SetPreference(isEnabled(job));

            card.SetGuidebookAvailable(job.Guides is { Count: > 0 });

            card.GuidebookClicked += () =>
            {
                if (job.Guides != null)
                {
                    OpenGuidebookRequested?.Invoke(job.Guides);
                }
            };

            // Locked jobs remain visible, so players can understand that they exist and inspect the unmet requirement tooltip
            if (!_requirements.IsAllowed(job, _profile, out var reason))
            {
                card.SetLocked(true);

                var tooltip = new Tooltip();
                tooltip.SetMessage(reason);
                card.TooltipSupplier = _ => tooltip;

                if (isEnabled(job))
                {
                    SetJobEnabled(job,false,false);
                }
            }
            else
            {
                card.SetLocked(false);
            }

            card.PreferenceChanged += enabled =>
            {
                SetJobEnabled(job, enabled);
            };

            var hasLoadout = _prototypeManager.TryIndex<RoleLoadoutPrototype>(LoadoutSystem.GetJobPrototype(job.ID), out _);

            card.SetLoadoutAvailable(hasLoadout);

            if (hasLoadout)
            {
                card.LoadoutClicked += () =>
                {
                    PreviewJobChanged?.Invoke(job);
                    LoadoutRequested?.Invoke(job);
                };
            }

            row!.AddChild(card);

            column = (column + 1) % 2;
        }

        if (row == null || column == 0)
            return;

        for (var index = column; index < 2; index++)
        {
            row.AddChild(new Control
            {
                HorizontalExpand = true,
            });
        }
    }

    private BoxContainer CreateCardRow()
    {
        return new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,

            HorizontalExpand = true,
            SeparationOverride = 8,

            Margin = new Thickness(0, 0, 0, 8),
        };
    }

    /// <summary>
    /// Updates the character profile to enable or disable a job, and refreshes the job list if requested.
    /// </summary>
    private void SetJobEnabled(JobPrototype job, bool enabled, bool refresh = true)
    {
        if (_profile == null)
            return;

        _profile =
            _profile.WithJobPriority(job.ID,
                enabled
                    ? JobPriority.Medium // TODO: Because we don't have multi-character support yet we just set this to medium for now when a job is enabled.
                    : JobPriority.Never);

        NotifyProfileChanged();

        if (refresh)
            RefreshJobs();
    }

    /// <summary>
    /// Raises the ProfileChanged event with the current character profile.
    /// </summary>
    private void NotifyProfileChanged()
    {
        if (_profile != null)
            ProfileChanged?.Invoke(_profile);
    }
}
