using Content.Client.Message;
using Content.Client.Resources;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starfall.UserInterface.Lobby.Roles;

/// <summary>
/// A card representing a job in the Starfall lobby.
/// Displays the job's name, description, and icon, and allows the user to view the job's guidebook, loadout, and set their preference for the job.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class StarfallJobCard : PanelContainer
{
    [Dependency] private IResourceCache _resourceCache = null!;

    private bool _suppressPreferenceEvent;
    private bool _guidebookAvailable;

    public event Action? GuidebookClicked;
    public event Action? LoadoutClicked;
    public event Action<bool>? PreferenceChanged;

    public StarfallJobCard()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        GuidebookButton.OnPressed += _ =>
        {
            if (_guidebookAvailable)
                GuidebookClicked?.Invoke();
        };

        LoadoutButton.OnPressed += _ => LoadoutClicked?.Invoke();
        PreferenceToggle.OnToggled += args =>
        {
            if (!_suppressPreferenceEvent)
                PreferenceChanged?.Invoke(args.Pressed);
        };

        JobDescription.OnResized += UpdateDescriptionHeight;
        OnResized += UpdateDescriptionHeight;
    }
    public void SetName(string name)
    {
        JobName.Text = name;

        // Adjust font size based on name length
        var fontSize = name.Length switch
        {
            > 24 => 12,
            > 18 => 13,
            _ => 15,
        };

        JobName.FontOverride = _resourceCache.GetFont("/Fonts/NotoSans/NotoSans-Bold.ttf", fontSize);
    }

    public void SetDescription(string description)
    {
        JobDescription.SetMarkupPermissive(description);
    }

    private void UpdateDescriptionHeight()
    {
        const float minimumDescriptionHeight = 72f;
        const float descriptionPadding = 14f;
        const float headerHeight = 66f;
        const float cardPadding = 16f;
        const float separation = 7f;

        // ᓚᘏᗢ <(I FUCKING HATE MATH, STOP MAKING ME DO MATHHHHHHHHH WAGGHHH
        var descriptionHeight = MathF.Max(minimumDescriptionHeight, JobDescription.DesiredSize.Y + descriptionPadding);
        var requiredCardHeight = headerHeight + separation + descriptionHeight + cardPadding;

        if (MathF.Abs(MinHeight - requiredCardHeight) < 0.5f)
            return;

        DescriptionPanel.MinHeight = descriptionHeight;
        MinHeight = requiredCardHeight;

        Control? current = this;
        while (current != null)
        {
            current.InvalidateMeasure();
            current.InvalidateArrange();
            current = current.Parent;
        }
    }

    public void SetIcon(Texture texture)
    {
        JobIcon.Texture = texture;
    }

    public void SetPreference(bool enabled)
    {
        _suppressPreferenceEvent = true;
        PreferenceToggle.Pressed = enabled;
        _suppressPreferenceEvent = false;
    }

    /// <summary>
    /// Sets whether the preference toggle is locked (disabled) or not.
    /// When locked, the toggle cannot be changed by the user.
    /// </summary>
    public void SetLocked(bool locked)
    {
        PreferenceToggle.Disabled = locked;
        Modulate = locked ? Color.FromHex("#687078") : Color.White; // ᓚᘏᗢ <(I love hardcoding colors
    }

    public void SetGuidebookAvailable(bool available)
    {
        _guidebookAvailable = available;
        GuidebookButton.ToolTip = available ? Loc.GetString("humanoid-profile-editor-guidebook-button-tooltip") : null;
    }

    public void SetLoadoutAvailable(bool available)
    {
        LoadoutButton.Visible = available;
    }
}
